// <auto-generated />
using EthernetSwitch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EthernetSwitch.Data.Migrations
{
    [DbContext(typeof(EthernetSwitchContext))]
    [Migration("20201111180009_AddedSNMPConfig")]
    partial class AddedSNMPConfig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("EthernetSwitch.Data.Models.SNMPMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Enterprise")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("TimeStamp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TrapMessages");
                });

            modelBuilder.Entity("EthernetSwitch.Data.Models.SNMPMessageVariable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrapMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariableId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrapMessageId");

                    b.ToTable("SNMPMessageVariable");
                });

            modelBuilder.Entity("EthernetSwitch.Data.Models.SNMPTrapUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Encryption")
                        .HasColumnType("TEXT");

                    b.Property<int>("EncryptionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TrapUsers");
                });

            modelBuilder.Entity("EthernetSwitch.Data.Models.SNMPUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Encryption")
                        .HasColumnType("TEXT");

                    b.Property<int>("EncryptionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SNMPUsers");
                });

            modelBuilder.Entity("EthernetSwitch.Data.Models.Settings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRegistration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowTagging")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HiddenInterfaces")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireConfirmation")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("EthernetSwitch.Data.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EthernetSwitch.Data.Models.SNMPMessageVariable", b =>
                {
                    b.HasOne("EthernetSwitch.Data.Models.SNMPMessage", "TrapMessage")
                        .WithMany("Variables")
                        .HasForeignKey("TrapMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EthernetSwitch.Data.Models.Settings", b =>
                {
                    b.OwnsOne("EthernetSwitch.Data.Models.SNMPConfiguration", "SNMPConfiguration", b1 =>
                        {
                            b1.Property<long>("SettingsId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AgentAddresses")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SysContact")
                                .HasColumnType("TEXT");

                            b1.Property<string>("SysLocation")
                                .HasColumnType("TEXT");

                            b1.Property<string>("TrapRecieverIpAddress")
                                .HasColumnType("TEXT");

                            b1.Property<int>("TrapRecieverPort")
                                .HasColumnType("INTEGER");

                            b1.HasKey("SettingsId");

                            b1.ToTable("Settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingsId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
