# Generated by Django 2.2.7 on 2020-01-05 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
