# Generated by Django 2.2.7 on 2020-01-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switch', '0002_delete_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Port',
            new_name='Interface',
        ),
    ]
